def encode_joint_for_modbus(angle_rad):
  return floor(angle_rad * 572.957795 + 10000.5)
end

q = get_actual_joint_positions()

write_port_register(128, encode_joint_for_modbus(q[0]))
write_port_register(129, encode_joint_for_modbus(q[1]))
write_port_register(130, encode_joint_for_modbus(q[2]))
write_port_register(131, encode_joint_for_modbus(q[3]))
write_port_register(132, encode_joint_for_modbus(q[4]))
write_port_register(133, encode_joint_for_modbus(q[5]))
